# Generated by Django 5.2.8 on 2025-11-12 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='alternatif',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='kriteria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.TextField()),
                ('tipe', models.CharField(choices=[('benefit', 'Benefit'), ('cost', 'Cost')], max_length=10)),
                ('bobot', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HasilBorda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skor', models.FloatField()),
                ('rangking', models.IntegerField()),
                ('alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alternatif')),
            ],
        ),
        migrations.CreateModel(
            name='stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NilaiEvaluasi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nilai', models.FloatField()),
                ('alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alternatif')),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kriteria')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stakeholder')),
            ],
        ),
        migrations.CreateModel(
            name='HasilWP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skor', models.FloatField()),
                ('alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alternatif')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stakeholder')),
            ],
        ),
    ]
